#Mini Assignment 1: Data Structures

This copy is non-editable. To create your own copy, go to File -> Save a copy in Drive. That makes an editable copy of your own that is stored in your Google Drive.

Please add only one code cell after each question and create a program to answer the question. Make sure your code runs without error. After you are finished, run your code to display the output, then click on File -> Print -> Save as PDF to create a PDF output and upload it on Brightspace.

**NOTE:** Make sure your PDF does not have your name or any identifying information in the name or content of the file. Anonymity is essential for the peer-review process.

##List

1. Run below code to create three variables each including a list with a first name, last name, and birth-year.

In [2]:
a = ['Xin', 'Zhu', '1995']
b = ['Marvin', 'Capenter', '1991']
c = ['Mara', 'Singh', '1988']

2. Create the code that combines the above three variables into a new list that includes all the items of the three previous lists. The new list should have nine items.

In [3]:
lists_combined = a + b + c
print(lists_combined)

['Xin', 'Zhu', '1995', 'Marvin', 'Capenter', '1991', 'Mara', 'Singh', '1988']

3. Print the last three items in the list. Make sure you use slicing technique.

In [4]:
print(lists_combined[-3:])

['Mara', 'Singh', '1988']

4. Print a list including the first names of the three people. Make sure you use slicing technique.

In [5]:
print(lists_combined[::3])

['Xin', 'Marvin', 'Mara']

5. Create a nested list that includes the three initial lists you created on the first step. It means your new nested list should have three items each of which is a list.

In [6]:
nested_list = [a, b, c]
print(nested_list)

[['Xin', 'Zhu', '1995'], ['Marvin', 'Capenter', '1991'], ['Mara', 'Singh', '1988']]

6. Print the information for the last two people from the nested list. Make sure you use slicing technique.

In [7]:
print(nested_list[-2:])

[['Marvin', 'Capenter', '1991'], ['Mara', 'Singh', '1988']]

7. Print the first name and second name of the second person from the nested list. Make sure you use slicing technique.

In [8]:
print(nested_list[1][:2])

['Marvin', 'Capenter']

8. Create and store a new list that has first name, last name and birth_year of a fourth person. Then, add this new list to your previous nested list of three people.

In [9]:
new_person = ['Gaius', 'Octavian', '1990']
new_nested_list = [nested_list, new_person]
print(new_nested_list)

[[['Xin', 'Zhu', '1995'], ['Marvin', 'Capenter', '1991'], ['Mara', 'Singh', '1988'], 'Gaius', 'Octavian', '1990']]

##Dictionary

9. Create and store a dictionary that includes first name, last name, age, city of residency, job, and like that of a person. Use a proper key name for each value.

In [10]:
person = {
    "first_name": "Ed",
    "last_name": "Sheeran",
    "age": 32,
    "city_of_residence": "London, UK",
    "job": "International Superstar",
    "highest_education": "I have NO idea"
}

10. Print the last name of the person from the dictionary.

In [ ]:
print(person["last_name"])

Sheeran

11. Change the city of residence in the dictionary to denver.

In [ ]:
person["city_of_residence"] = "Denver, CO"
print(person["city_of_residence"])

Denver, CO

12. Add a new piece of info for the person to the dictionary, like favorite color.

In [ ]:
person["favorite_color"] = "blue"
print(person["favorite_color"])

blue

13. Use keys() , values(), and items() methods to return the keys, values, and items in your dictionary.

In [ ]:
print(person.keys())
print(person.values())
print(person.items())

dict_keys(['first_name', 'last_name', 'age', 'city_of_residence', 'job', 'highest_education', 'favorite_color'])
dict_values(['Ed', 'Sheeran', 32, 'Denver, CO', 'International Superstar', 'I have NO idea', 'blue'])
dict_items([('first_name', 'Ed'), ('last_name', 'Sheeran'), ('age', 32), ('city_of_residence', 'Denver, CO'), ('job', 'International Superstar'), ('highest_education', 'I have NO idea'), ('favorite_color', 'blue')])

##Set

14. Create and store a set including different datatypes. Put some duplicate values in the set. Print the set to see the result.

In [ ]:
wonky_set = {1, 1.5, 1.5, "how's it going", "pretty good", "how's it going", False, True, False, (1,2), (1,2)}
print(wonky_set)

{False, 1, 1.5, (1, 2), "how's it going", 'pretty good'}

15. **Challenge:** create a list that includes unique items of the two following lists.

In [ ]:
listone=[1,2,3,4,5,6,7]
listtwo=[4,5,6,7,8,9,10]
dupe_free_list = list(set(listone + listtwo))
print(dupe_free_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]