#Mini Assignment 4. Function
Please add one code cell after each question and create a program to answer the question. Make sure your code runs without error. After you are finished, click on File -> Print -> Save as PDF to create a PDF output and upload it on Brightspace.

NOTE: Make sure your PDF does not have your name or any identifying information in the name or content of the file. Anonymity is essential for the peer-review process.

##Pre-defined function

1. Use [zip()](https://docs.python.org/3.3/library/functions.html#zip) function on the fname and lname lists to create fullname list. Then use the [sorted()](https://docs.python.org/3.3/library/functions.html#sorted) function to return the names sorted alphabetically.

In [ ]:
fname = ['Ashkan', 'Alex', 'Zamir', 'Xin']
lname = ['Sani', 'Wolkof', 'Zaman', 'Lee']

In [ ]:
# Since zip returns a 2-length tuple, you can have two variables in the for loop meaning concatenation is easy
full_name_list = [f"{first_name} {last_name}" for first_name, last_name in zip(fname, lname)]
full_name_sorted_list = sorted(full_name_list)

print(full_name_sorted_list)

['Alex Wolkof', 'Ashkan Sani', 'Xin Lee', 'Zamir Zaman']

##User-defined functions

2. What does the following function do? Run the code and see what happens. Why does the code line 5 prints x but the code line 6 results in the "NameError: name 'x' is not defined"? Explain in few sentences here.

In [ ]:
def myfunc():
	x = 10
	print("Value inside function:",x)

myfunc()
print("Value outside function:",x)

##This is happening because x = 10 is a local variable, so it stays inside the function.  It would have to be a global variable defined outside of the function to be used in that context.

3. Create a function called sumall that receives two arguments as the start number, and the stop number. The functions should return the sum of all numbers in between the two inclusive. Next, call the function to make sure it works well.

In [2]:
def num_func(start, stop):
  total = 0
  # Include the numbers in the calculation
  for num in range(start, stop+1):
    # Increase total with every iterations
    total += num
  # Return the total variable
  return total

num_func(3, 15)

117

4. Create a function that receives ONE list (only one argument) and returns the list with only items that include any of the vowels in them. Vowels include a, e, i, o, u. Next call the function to make sure it works fine.

In [ ]:
def vowel_list(listy):
  new_list = []
  # Iterate over items in list
  for item in listy:
    # Iterate over chars in item
    for char in item:
      # If char is a vowel, add it to the new_list and break from inner for loop
      if char in 'AEIOUaeiou':
        new_list.append(item)
        break
  # Return new_list
  return new_list

vowel_list(['hello', 'hows', 'it', 'hanging', 'fhggdggfjfkg', 'sddfffffff'])

['hello', 'hows', 'it', 'hanging']

## Anonymous functions

5. Use an anonymous function inside the [filter()](https://docs.python.org/3.3/library/functions.html#filter) function to filter namelist for only one-part names in the namelist. Make sure you convert the result to a list if it is not already a list.

In [ ]:
namelist = ['Arvin', 'John Paul ', 'Mary Jo', 'Kayvan',
            'Xinyu', 'Dominique', 'Daniel Dae Kim']
# Check if there is no space in the name after it is stripped of whitespace
one_part_names = filter(lambda name: ' ' not in name.strip(), namelist)
print(list(one_part_names))

['Arvin', 'Kayvan', 'Xinyu', 'Dominique']

6. Use an anonymous function inside the [map()](https://docs.python.org/3.3/library/functions.html#map) function to add 5 units to all the items in numlist. Make sure you convert the result to a list if it is not already a list.

In [ ]:
numlist = [12, 32, 45, 6, 10, 22, 108]
# Adding 5 unites to all items within numlist using lambda function
add_list = list(map(lambda number: number + 5, numlist))
print(add_list)

[17, 37, 50, 11, 15, 27, 113]

I used ChatGPT to get me started on a couple problems so here is the link if you would like to check it out!  https://chat.openai.com/share/2e23853a-209b-408d-a405-1308e749b9c9